/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui.components;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javaeproject.model.MenuModal;

/**
 *
 * @author DELL
 */
public class MenuItem extends javax.swing.JPanel {
    private boolean selected;
    private boolean hovered;
    /**
     * Creates new form MenuItem
     */
    public MenuItem(MenuModal data) {
        initComponents();
        if (data.getType() == MenuModal.MenuType.MENU) {
            jLabelIcon.setIcon(data.toIcon());
            jLabelText.setText(data.getName());
        }
        else if (data.getType() == MenuModal.MenuType.LOGOUT) {
            jLabelIcon.setIcon(data.toIcon());
            jLabelText.setText(data.getName());
        }
        else if (data.getType() == MenuModal.MenuType.EMPTY) {
            
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcon = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelText.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelIcon)
                .addGap(10, 10, 10)
                .addComponent(jLabelText)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jLabelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        if (selected) {
            g2.setColor(new Color(255,255,255, 60));
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 5, 5);
        }
        else if (hovered) {
            g2.setColor(new Color(255,255,255, 20));
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 5, 5);
        }
        
        
        super.paintComponent(g); 
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public void setHovered(boolean hovered) {
        this.hovered = hovered;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelText;
    // End of variables declaration//GEN-END:variables
}
