/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui;

import java.sql.Connection;
import javaeproject.connection.ConnectionDB;
import javaeproject.dao.DepartmentDAO;
import javax.swing.JOptionPane;
import javaeproject.model.DoctorAndReceptionist;
import javaeproject.dao.DoctorAndReceptionistDAO;

/**
 *
 * @author DELL
 */
public class AssignToDepartmentGUI extends javax.swing.JPanel {
    private Connection connection;
    /**
     * Creates new form AssignToDepartment
     */
    public AssignToDepartmentGUI() {
        initComponents();
        connection = ConnectionDB.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emId = new javax.swing.JTextField();
        showBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nametextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gendertextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        positiontextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        currentDepartmentID = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        change = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        departmenttext = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Assign Doctor and Receptionist to Department");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Enter Employee ID");

        showBt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        showBt.setText("Show Information");
        showBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Name");

        nametextfield.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Gender");

        gendertextfield.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Position");

        positiontextfield.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Current DepartmentID");

        currentDepartmentID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptionist Department", "Radiology Department", "Outpatient Department", "Operating Theatre" }));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Assign to Department");

        change.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        change.setText("Change");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Current Department");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(69, 69, 69)
                                .addComponent(emId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positiontextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(departmenttext, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gendertextfield)
                    .addComponent(showBt)
                    .addComponent(currentDepartmentID, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(change))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showBt))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(gendertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(positiontextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(currentDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmenttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(change)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtActionPerformed
        String employeeID = emId.getText();

    // Kiểm tra nếu EmployeeID rỗng, hiển thị thông báo lỗi
    if (employeeID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an Employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Gọi DAO để lấy thông tin nhân viên
    DoctorAndReceptionistDAO dao = new DoctorAndReceptionistDAO();
    DoctorAndReceptionist employeeInfo = dao.getEmployeeInformation(employeeID);

    // Kiểm tra xem thông tin có tồn tại
    if (employeeInfo == null) {
        JOptionPane.showMessageDialog(this, "No employee found with this Employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lấy DepartmentID từ thông tin nhân viên
    String departmentID = employeeInfo.getCurrentDepartment();

    // Gọi DAO để lấy thông tin DepartmentName dựa trên DepartmentID
    DepartmentDAO departmentDAO = new DepartmentDAO();
    String departmentName = departmentDAO.getNameByID(departmentID);

    // Hiển thị thông tin lên các JTextField
    nametextfield.setText(employeeInfo.getName());
    gendertextfield.setText(employeeInfo.getGender());
    positiontextfield.setText(employeeInfo.getPosition());
    currentDepartmentID.setText(departmentID);
    departmenttext.setText(departmentName);
    }//GEN-LAST:event_showBtActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        String employeeID = emId.getText();
    String selectedDepartmentName = (String) jComboBox1.getSelectedItem();

    // Kiểm tra xem Employee ID có trống không
    if (employeeID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kiểm tra xem Position có phải Doctor hoặc Receptionist không
    DoctorAndReceptionistDAO dao = new DoctorAndReceptionistDAO();
    DoctorAndReceptionist employeeInfo = dao.getEmployeeInformation(employeeID);
    if (employeeInfo == null) {
        JOptionPane.showMessageDialog(this, "No employee found with this Employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String currentPosition = employeeInfo.getPosition();
    if (!("Doctor".equals(currentPosition) || "Receptionist".equals(currentPosition))) {
        JOptionPane.showMessageDialog(this, "This employee is not a Doctor or Receptionist.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Gọi DAO để lấy DepartmentID dựa trên DepartmentName
    DepartmentDAO departmentDAO = new DepartmentDAO();
    String departmentID = departmentDAO.getDepartmentIDbyDepartmentName(selectedDepartmentName);

    if (departmentID == null) {
        // Xử lý trường hợp không tìm thấy DepartmentID tương ứng
        JOptionPane.showMessageDialog(this, "Department not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Thực hiện cập nhật DepartmentID trong bảng Employee
    boolean success = dao.updateDoctorPosition(employeeID, departmentID);

    if (success) {
        // Hiển thị thông báo thành công nếu cập nhật thành công
        JOptionPane.showMessageDialog(this, "Department ID updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Hiển thị thông báo lỗi nếu cập nhật thất bại
        JOptionPane.showMessageDialog(this, "Error updating Department ID.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_changeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change;
    private javax.swing.JTextField currentDepartmentID;
    private javax.swing.JTextField departmenttext;
    private javax.swing.JTextField emId;
    private javax.swing.JTextField gendertextfield;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nametextfield;
    private javax.swing.JTextField positiontextfield;
    private javax.swing.JButton showBt;
    // End of variables declaration//GEN-END:variables
}
