/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui;

import java.awt.Color;
import java.util.ArrayList;
import javaeproject.dao.ShiftDAO;
import javaeproject.dao.ShiftRequestDAO;
import javaeproject.events.EventSelected;
import javaeproject.model.ShiftRequest;
import javaeproject.model.User;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DELL
 */
public class CheckStatusShiftRequestGUI extends javax.swing.JPanel {

    private final ShiftRequestDAO shiftRequestDAO = new ShiftRequestDAO();
    private final ShiftDAO shiftDAO = new ShiftDAO();
    private ArrayList<ShiftRequest> shiftRequests;
    private EventSelected event;
    
    public void addEventSelected(EventSelected event) {
        this.event = event;
        table.addEventSelected(event);
    }
    
    public CheckStatusShiftRequestGUI(User user) {
        initComponents();
        init(user);
        spTable.getViewport().setOpaque(false);
        table.setTypeOfTable("CheckStatusShiftRequest");
        shiftDetailsPanel1.setVisible(false);
        shiftDetailsPanel2.setVisible(false);
        addEventSelected(new EventSelected() {
            @Override
            public void setSelected(Object item) {
                shiftDetailsPanel1.setVisible(true);
                shiftDetailsPanel2.setVisible(true);
                shiftDetailsPanel1.setShift(shiftDAO.getByID(shiftRequests.get((int) item).getCurrentShiftID()));
                shiftDetailsPanel2.setShift(shiftDAO.getByID(shiftRequests.get((int) item).getDesiredShiftID()));
            }
            
        });
        
    }

    
    private void init(User user) {
        this.shiftRequests = shiftRequestDAO.getAllUserRequest(user.getEmployeeID());
        for (ShiftRequest item : shiftRequests) {
            table.addRow(new Object[] {item.getCurrentShiftID(), item.getDesiredShiftID(), item.getDetails(), item.getDate(), item.getStatus()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shiftDetailsPanel1 = new javaeproject.gui.components.ShiftDetailsPanel();
        shiftDetailsPanel2 = new javaeproject.gui.components.ShiftDetailsPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new javaeproject.gui.components.MyTable();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("LIST OF SHIFT REQUEST");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("CURRENT SHIFT");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("DESIRED SHIFT");

        spTable.setOpaque(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Current Shift", "DesireShift", "Reason", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setOpaque(false);
        spTable.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shiftDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(shiftDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shiftDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shiftDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javaeproject.gui.components.ShiftDetailsPanel shiftDetailsPanel1;
    private javaeproject.gui.components.ShiftDetailsPanel shiftDetailsPanel2;
    private javax.swing.JScrollPane spTable;
    private javaeproject.gui.components.MyTable table;
    // End of variables declaration//GEN-END:variables
}
