/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui;

import java.awt.Color;
import java.util.ArrayList;
import javaeproject.dao.ShiftRequestDAO;
import javaeproject.model.ShiftRequest;
import javaeproject.model.User;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DELL
 */
public class CheckStatusShiftRequestGUI extends javax.swing.JPanel {

    private final ShiftRequestDAO shiftRequestDAO = new ShiftRequestDAO();
    public CheckStatusShiftRequestGUI(User user) {
        initComponents();
        init(user);
        spTable.getViewport().setOpaque(false);
    }

    
    private void init(User user) {
        ArrayList<ShiftRequest> shiftRequestList = shiftRequestDAO.getAllUserRequest(user.getEmployeeID());
        for (ShiftRequest item : shiftRequestList) {
            table.addRow(new Object[] {item.getCurrentShiftID(), item.getDesiredShiftID(), item.getDetails(), item.getDate(), item.getStatus()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        table = new javaeproject.gui.components.MyTable("CheckStatusShiftRequest");
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        spTable.setBackground(new java.awt.Color(255, 255, 255));
        spTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        spTable.setViewportView(table);

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Current Shift", "Desired Shift", "Reason", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        spTable.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("LIST OF SHIFT REQUEST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane spTable;
    private javaeproject.gui.components.MyTable table;
    // End of variables declaration//GEN-END:variables
}
