/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui;

import javaeproject.dao.*;
import javaeproject.model.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Admin
 */
public class ManageDoctorAndReceptionestGUI extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorAndReceptionestGUI
     */           
    public ManageDoctorAndReceptionestGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Manage Doctor and Receptionest");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(372, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            AddDoctorAndReceptionestGUI newAdd = new AddDoctorAndReceptionestGUI();
            newAdd.setVisible(true);
            JFrame newAddFrame = new JFrame();
            newAddFrame.setUndecorated(true);
            newAddFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            newAddFrame.setVisible(true);
            newAddFrame.setSize(1263, 780);
            newAddFrame.setLocationRelativeTo(null);
            newAddFrame.add(newAdd);
            JButton addBackbtn = new JButton();
            addBackbtn.setText("Back");
            addBackbtn.setBounds(50, 50, 75, 35);
            newAdd.add(addBackbtn);
            addBackbtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed (ActionEvent e) {
                    newAddFrame.dispose();
                }        
            });
        } catch (SQLException ex) {
            Logger.getLogger(ManageDoctorAndReceptionestGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            AlterDoctorAndReceptionest newAlter = new AlterDoctorAndReceptionest();
            newAlter.setVisible(true);
            JFrame newAlterFrame = new JFrame();
            newAlterFrame.setUndecorated(true);
            newAlterFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            newAlterFrame.setVisible(true);
            newAlterFrame.setSize(1263, 780);        
            newAlterFrame.setLocationRelativeTo(null);
            newAlterFrame.add(newAlter);
            JButton alterBackbtn = new JButton();
            alterBackbtn.setText("Back");
            alterBackbtn.setBounds(50, 50, 75, 35);
            newAlter.add(alterBackbtn);
            alterBackbtn.addActionListener(new ActionListener() {        
                @Override
                public void actionPerformed (ActionEvent e) {                
                    newAlterFrame.dispose();
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(ManageDoctorAndReceptionestGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            DeleteDoctorAndReceptionest newDelete = new DeleteDoctorAndReceptionest();
            newDelete.setVisible(true);
            JFrame newDeleteFrame = new JFrame();
            newDeleteFrame.setUndecorated(true);
            newDeleteFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            newDeleteFrame.setVisible(true);
            newDeleteFrame.setSize(1263, 780);        
            newDeleteFrame.setLocationRelativeTo(null);
            newDeleteFrame.add(newDelete);
            JButton deleteBackbtn = new JButton();
            deleteBackbtn.setText("Back");
            deleteBackbtn.setBounds(50, 50, 75, 35);
            newDelete.add(deleteBackbtn);
            deleteBackbtn.addActionListener(new ActionListener() {        
                @Override
                public void actionPerformed (ActionEvent e) {                
                    newDeleteFrame.dispose();
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(ManageDoctorAndReceptionestGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            SearchDoctorAndReceptionest newDelete = new SearchDoctorAndReceptionest();
            newDelete.setVisible(true);
            JFrame newDeleteFrame = new JFrame();
            newDeleteFrame.setUndecorated(true);
            newDeleteFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            newDeleteFrame.setVisible(true);
            newDeleteFrame.setSize(1263, 780);        
            newDeleteFrame.setLocationRelativeTo(null);
            newDeleteFrame.add(newDelete);
            JButton deleteBackbtn = new JButton();
            deleteBackbtn.setText("Back");
            deleteBackbtn.setBounds(50, 50, 75, 35);
            newDelete.add(deleteBackbtn);
            deleteBackbtn.addActionListener(new ActionListener() {        
                @Override
                public void actionPerformed (ActionEvent e) {                
                    newDeleteFrame.dispose();
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(ManageDoctorAndReceptionestGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
