/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaeproject.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JRootPane;

/**
 *
 * @author Admin
 */
public class ManageDepartmentGUI extends javax.swing.JPanel {

    /**
     * Creates new form ManageDepartmentGUI
     */
    public ManageDepartmentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Department");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Alter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            AddDepartment newAdd = new AddDepartment();
            newAdd.setVisible(true);
            JFrame newAddFrame = new JFrame();
            newAddFrame.setUndecorated(true);
            newAddFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            newAddFrame.setVisible(true);
            newAddFrame.setSize(1263, 780);
            newAddFrame.setLocationRelativeTo(null);
            newAddFrame.add(newAdd);
            JButton addBackbtn = new JButton();
            addBackbtn.setText("Back");
            addBackbtn.setBounds(50, 50, 75, 35);
            newAdd.add(addBackbtn);
            addBackbtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed (ActionEvent e) {
                    newAddFrame.dispose();
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(ManageDepartmentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AlterDepartment newAdd = new AlterDepartment();
        newAdd.setVisible(true);
        JFrame newAddFrame = new JFrame();
        newAddFrame.setUndecorated(true);
        newAddFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        newAddFrame.setVisible(true);
        newAddFrame.setSize(1263, 780);        
        newAddFrame.setLocationRelativeTo(null);
        newAddFrame.add(newAdd);
        JButton addBackbtn = new JButton();
        addBackbtn.setText("Back");
        addBackbtn.setBounds(50, 50, 75, 35);
        newAdd.add(addBackbtn);
        addBackbtn.addActionListener(new ActionListener() {        
            @Override
            public void actionPerformed (ActionEvent e) {                
                newAddFrame.dispose();
            }
        });  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DeleteDepartment newAdd = new DeleteDepartment();
        newAdd.setVisible(true);
        JFrame newAddFrame = new JFrame();
        newAddFrame.setUndecorated(true);
        newAddFrame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        newAddFrame.setVisible(true);
        newAddFrame.setSize(1263, 780);        
        newAddFrame.setLocationRelativeTo(null);
        newAddFrame.add(newAdd);
        JButton addBackbtn = new JButton();
        addBackbtn.setText("Back");
        addBackbtn.setBounds(50, 50, 75, 35);
        newAdd.add(addBackbtn);
        addBackbtn.addActionListener(new ActionListener() {        
            @Override
            public void actionPerformed (ActionEvent e) {                
                newAddFrame.dispose();
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
